id: P009150
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4942
  title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་འགྲེལ་པ་ལེགས་པར་བཤད་པ།
  author: ''
  volumes:
    780fc295f9c34d07be88cb36098bb733:
      image_group_id: I1KG5058
      title: ''
      volume_number: 1
      total_pages: 478
