id: IBBD0A71B
legacy_id: P009150
ocr_import_info:
  bdrc_scan_id: W1KG4942
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T13:04:19'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T17:10:06.354688+00:00'
last_modified: 2022-09-01 01:10:19.771266
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4942
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4942
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པའི་འགྲེལ་པ་ལེགས་པར་བཤད་པ།
  author: རཀ་ར་ཐུབ་བསྟན་ཆོས་དར།
statistics:
  ocr_word_mean_confidence_index: 0.8505911177340704
  ocr_word_median_confidence_index: 0.9399999976158142
quality: null
bases:
  I1KG5058:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5058
      total_pages: 478
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG5058.txt
    statistics:
      ocr_word_median_confidence_index: 0.9399999976158142
      ocr_word_mean_confidence_index: 0.8505911177340704
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
